apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predict-api
  template:
    metadata:
      labels:
        app: predict-api
    spec:
      containers:
      - name: predict-api
        image: modeha/my-ml-api:latest
        ports:
        - containerPort: 5000
