data:
  interval: 'H'
  path: './dataset/'
  index_column: 'date_creation'
  index: 5

model:
  model_type: 'transformer'  # Choose between 'lstm', 'lstm_cnn', and 'transformer'
  prediction_period: 336
  n_in: 1
  n_out: 5
  lstm_units: 500
  dropout_rate: 0.2
  n: 28
  cnn_filters: 64
  cnn_kernel_size: 3
  num_heads: 4
  key_dim: 64
  ff_dim: 256

training:
  learning_rate: 0.001
  loss_function: 'mae'
  epochs: 100
  batch_size: 256

evaluation:
  y_limits: null
  plot_filename: './output/'
  model_name: 'Transformer_forecast'
  save_plots: true
  loss_plot_filename: './output/'
